### ISSUE TITLE
Problem with async/promises?

### ISSUE THREAD

**Issue by sebdeckers** [post-org/post-load-plugins#72]
I'm trying to use `posthtml` CLI with the `nanohtml` plugin which returns a promise. Unfortunately `posthtml` renders the output before the promise from `nanohtml` resolves. I might be wrong but I think the problem lies in how `post-load-plugins` ignores promises and calls `res()` (the callback) before even invoking the plugin, and completely ignoring the returned tree. See: https://github.com/post-org/post-load-plugins/blob/master/src/index.js#L37

**Comment by GitScrum** [comment]
related https://github.com/post-org/post-config/issues/62

**Comment by GitScrum** [comment]
@sebdeckers watch [PR](https://github.com/posthtml/posthtml-cli/pull/161)

**Comment by GitScrum** [comment]
@sebdeckers now you need update/reinstall posthtml-cli. Thanks for feedback.
